<?php

namespace App\Http\Controllers\Trainer;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Course;
use App\Models\User;
use App\Models\Purchase;
use App\Models\Payment;

class ReportController extends Controller
{
    public function index()
    {
        $trainer = Auth::guard('trainer')->user();

        // ✅ Get all trainer course IDs
        $trainerCourseIds = Course::where('trainer_id', $trainer->id)->pluck('id');

        // ✅ Total courses by this trainer
        $totalCourses = $trainerCourseIds->count();

        // ✅ Total unique students enrolled in trainer's courses
        $totalStudents = Purchase::whereIn('course_id', $trainerCourseIds)
            ->distinct('user_id')
            ->count('user_id');

        // ✅ Completed courses (optional placeholder)
        $completedCourses = 0;

        // ✅ Average rating (placeholder if rating table exists)
        $avgRating = 0;

        // ✅ Total revenue generated by trainer (from payments table)
        $totalRevenue = Payment::whereIn('course_id', $trainerCourseIds)
            ->sum('amount');

        return view('trainer.report', compact(
            'trainer',
            'totalCourses',
            'totalStudents',
            'completedCourses',
            'avgRating',
            'totalRevenue'
        ));
    }
}
